export const exerciseLookups = {
  bodyParts: {
    "1": "Thighs",
    "2": "Chest",
    "3": "Hips",
    "4": "Back",
    "5": "Upper Arms",
    "6": "Shoulders",
    "7": "Forearms",
    "8": "Calves",
    "9": "Neck",
    "10": "Cardio",
    "11": "Full body",
    "12": "Waist",
    "13": "Plyometrics",
    "14": "Weightlifting",
    "15": "Yoga",
    "16": "Stretching",
    "17": "Biceps",
    "18": "Triceps",
    "19": "Quadriceps",
    "20": "Hamstrings",
  },
  equipment: {
    "1": "Barbell",
    "2": "Body weight",
    "3": "Cable",
    "4": "Dumbbell",
    "5": "EZ Barbell",
    "6": "Leverage machine",
    "7": "Sled machine",
    "8": "Smith machine",
    "9": "Weighted",
    "10": "Assisted",
    "11": "Band",
    "12": "Battling Rope",
    "13": "Bosu ball",
    "14": "Hammer",
    "15": "Kettlebell",
    "16": "Medicine Ball",
    "17": "Olympic barbell",
    "18": "Power Sled",
    "19": "Resistance Band",
    "20": "Roll",
    "21": "Rollball",
    "22": "Rope",
    "23": "Stability ball",
    "24": "Stick",
    "25": "Suspension",
    "26": "Trap bar",
    "27": "Vibrate Plate",
    "28": "Wheel roller",
  },
  muscles: {
    "2": "ADDUCTOR_LONGUS",
    "3": "ADDUCTOR_MAGNUS",
    "4": "BICEPS_BRACHII",
    "5": "BRACHIALIS",
    "6": "BRACHIORADIALIS",
    "7": "DEEP_HIP_EXTERNAL_ROTATORS",
    "8": "DELTOID_ANTERIOR",
    "9": "DELTOID_LATERAL",
    "10": "DELTOID_POSTERIOR",
    "11": "ERECTOR_SPINAE",
    "12": "GASTROCNEMIUS",
    "13": "GLUTEUS_MAXIMUS",
    "14": "GLUTEUS_MEDIUS",
    "15": "GLUTEUS_MINIMUS",
    "16": "GRACILIS",
    "17": "HAMSTRINGS",
    "18": "ILIOPSOAS",
    "19": "INFRASPINATUS",
    "20": "LATISSIMUS_DORSI",
    "21": "LEVATOR_SCAPULAE",
    "22": "OBLIQUES",
    "23": "PECTINEOUS",
    "24": "PECTORALIS_MAJOR_CLAVICULAR_HEAD",
    "25": "PECTORALIS_MAJOR_STERNAL_HEAD",
    "26": "POPLITEUS",
    "27": "QUADRICEPS",
    "28": "RECTUS_ABDOMINIS",
    "29": "SARTORIUS",
    "31": "SERRATUS_ANTERIOR",
    "32": "SOLEUS",
    "33": "SPLENIUS",
    "34": "STERNOCLEIDOMASTOID",
    "35": "SUBSCAPULARIS",
    "36": "TENSOR_FASCIAE_LATAE",
    "37": "TERES_MAJOR",
    "38": "TERES_MINOR",
    "39": "TIBIALIS_ANTERIOR",
    "40": "TRANSVERSE_ABDOMINUS",
    "41": "TRAPEZIUS_LOWER_FIBERS",
    "42": "TRAPEZIUS_MIDDLE_FIBERS",
    "43": "TRAPEZIUS_UPPER_FIBERS",
    "44": "TRICEPS_BRACHII",
    "45": "WRIST_EXTENSORS",
    "46": "WRIST_FLEXORS",
  },
} as const;

export type ExerciseLookup = keyof typeof exerciseLookups;
