packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  lefthook: true
  workerd: true
catalog:
  dotenv: ^17.4.2
  zod: ^4.6.0
  "@types/node": ^26.5.1
  hono: ^4.13.7
  "@orpc/server": 2.0.0-beta.35
  "@orpc/openapi": 2.0.0-beta.35
  "@orpc/zod": 2.0.0-beta.35
  better-auth: 1.7.4
  lucide-react: ^1.44.0
  next-themes: ^0.4.6
  sonner: ^2.0.8
  typescript: ^6.0.3
  "@orpc/tanstack-query": 2.0.0-beta.35
  "@orpc/client": 2.0.0-beta.35
  "@tanstack/react-query": ^5.102.8
  "@tanstack/react-form": ^1.33.5
  "@types/react-dom": ^19.3.0
  tailwindcss: ^4.3.3
  "@better-auth/expo": 1.7.4
